<?php

require_once(dirname(__FILE__).'/autoload.php');

define("DRUPAL_WEBDAV_URL", 'davsrv');
define("DOCUMENT_ROOT", '/sharing');

/**
 * Implementation of hook_menu
 */
function davsrv_menu() {
    $items = array (
        DRUPAL_WEBDAV_URL => array (
            'page callback' => 'entry_point',
            'type' => MENU_CALLBACK,
            'access arguments' => array('access content'),
        ),
    );
    return $items;
}

/**
 * Implementation of hook_permission
 */
function davsrv_permission() {
    return array (
        'Webdav access' => array (
            'title' => t('Webdav access'),
            'restrict access' => true
        )
    );
}

function entry_point() {
    $server = ezcWebdavServer::getInstance();
    $router = new WebdavDrupalRouter();
    $router
        ->setDrupalUrlRoot(DRUPAL_WEBDAV_URL)
        ->setDocumentRoot(DOCUMENT_ROOT)
        //        ->setRootCollection(array('sharing', 'partage'))
        ;

    $server->auth = new WebdavDrupalAuth($router);

    $backend = WebdavDrupalBackend::getInstance($router);
        
    $server->handle($backend);
}
