<?php
require_once(dirname(__FILE__).'/vendors/IMAG/Autoloader/Autoloader.php');
require_once(dirname(__FILE__).'/vendors/ezcomponents/Base/src/base.php');

use IMAG\Autoloader\Autoloader,
    IMAG\davSrv\Backend\Backend,
    IMAG\davSrv\Router\Router,
    IMAG\davSrv\Authentication\Authentication
    ;

$loader = new Autoloader();
$loader->register();
spl_autoload_register("ezcBase::autoload");

define("DRUPAL_WEBDAV_URL", 'davsrv');
define("DOCUMENT_ROOT", '/sharing');

/**
 * Implementation of hook_menu
 */
function davsrv_menu() {
    $items = array (
        DRUPAL_WEBDAV_URL => array (
            'page callback' => 'entry_point',
            'type' => MENU_CALLBACK,
            'access arguments' => array('access content'),
        ),
    );

    return $items;
}

/**
 * Implementation of hook_permission
 */
function davsrv_permission() {
    return array (
        'Webdav access' => array (
            'title' => t('Webdav access'),
            'restrict access' => true
        )
    );
}

function entry_point() {

    $server = ezcWebdavServer::getInstance();

    $router = new Router();
    $router
        ->setDrupalUrlRoot(DRUPAL_WEBDAV_URL)
        ->setDocumentRoot(DOCUMENT_ROOT)
        //        ->setRootCollection(array('sharing', 'partage'))
        ;

    $server->auth = new Authentication($router);

    $backend = Backend::getInstance()
        ->setRouter($router)
        //        ->setExtensionCheck()
        ;
        
    $server->handle($backend);
}
